# syntax=docker.io/docker/dockerfile:1

FROM node:20.17.0-alpine AS base

FROM base AS deps
WORKDIR /app
RUN apk add --no-cache libc6-compat
RUN apk add --update npm
RUN npm install -g npm@latest
COPY package.json package-lock.json* ./
RUN npm ci

FROM base AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .
RUN npm run build

FROM base AS runner
WORKDIR /app
ENV NODE_ENV=development
ENV NEXT_TELEMETRY_DISABLED=1
RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs
# COPY --from=deps /app/public ./public
# RUN mkdir .next
# RUN chown nextjs:nodejs .next
# COPY --from=deps --chown=nextjs:nodejs /app/.next/standalone ./
# COPY --from=deps --chown=nextjs:nodejs /app/.next/static ./.next/static
USER nextjs
EXPOSE 3000
ENV PORT=3000
CMD HOSTNAME='0.0.0.0' npm run dev
