const testNameMap: Record<string, string> = {
  ALB2: 'Albumin',
  ALP2S: 'Alkaline Phosphatase',
  ALTL: 'Alanine Aminotransferase',
  AMYL2: 'Amylase',
  ASTL: 'Aspartate Aminotransferase',
  BILD2: 'Direct Bilirubin',
  BILT3: 'Total Bilirubin',
  CA2: 'Calcium',
  CHOL2: 'Total Cholesterol',
  CK2: 'Creatine Kinase',
  CKMB2: 'Creatine Kinase-MB',
  'CL-I': 'Chloride',
  CREJ2: 'Creatinine',
  CRP4: 'C-Reactive Protein',
  GGTI2: 'Gamma-Glutamyl Transferase',
  GLUC3: 'Glucose',
  HDLC4: 'HDL Cholesterol',
  'K-I': 'Potassium',
  LDHI2: 'Lactate Dehydrogenase',
  LIP: 'Lipase',
  'MG-2': 'Magnesium',
  'NA-I': 'Sodium',
  PHOS2: 'Phosphorus',
  TRIGL: 'Triglycerides',
  UA2: 'Uric Acid',
  UREL: 'Urea',
  'TAP-20': 'Activated Partial Thromboplastin Time',
  TTPA: 'Prothrombin Time',
  WBC: 'White Blood Cells',
  RBC: 'Red Blood Cells',
  HGB: 'Hemoglobin',
  HCT: 'Hematocrit',
  MCV: 'Mean Corpuscular Volume',
  MCH: 'Mean Corpuscular Hemoglobin',
  MCHC: 'Mean Corpuscular Hemoglobin Concentration',
  'RDW-CV': 'Red Cell Distribution Width',
  PLT: 'Platelets',
  'NEU#': 'Absolute Neutrophils',
  'LYM#': 'Absolute Lymphocytes',
  'MON#': 'Absolute Monocytes',
  'EOS#': 'Absolute Eosinophils',
  'BAS#': 'Absolute Basophils',
  'NRBC%': 'Nucleated Red Blood Cells Percentage',
  'NRBC#': 'Absolute Nucleated Red Blood Cells',
  'NEU%': 'Neutrophils Percentage',
  'LYM%': 'Lymphocytes Percentage',
  'MON%': 'Monocytes Percentage',
  'EOS%': 'Eosinophils Percentage',
  'BAS%': 'Basophils Percentage',
};

const returnFullNameByTest = (test: string) => testNameMap[test] || test;

export default returnFullNameByTest;
